version: '3'
services:
  windows-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-windows-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_windows_api:/usr/lib/python3.8/site-packages/vlab_windows_api
    command: ["python3", "app.py"]

  windows-worker:
    image:
      willnx/vlab-windows-worker
    volumes:
      - ./vlab_windows_api:/usr/lib/python3.8/site-packages/vlab_windows_api
      - /mnt/raid/images/windows:/images:ro
    environment:
      - INF_VCENTER_SERVER=changeME
      - INF_VCENTER_USER=changeME
      - INF_VCENTER_PASSWORD=changeME
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  windows-broker:
    image:
      rabbitmq:3.7-alpine
